INSERT INTO public.categories (name, slug, description, icon, sort_order) VALUES
('AI Tools','ai-tools','Chat assistants, writing helpers, image and audio generation.','sparkles',1),
('Education & Learning','education','Online courses, coding practice and language learning.','graduation-cap',2),
('Delivery & Shopping','delivery-shopping','Groceries, food delivery and online marketplaces.','shopping-bag',3),
('Website Builders','website-builders','Build and publish websites with or without code.','layout-template',4),
('Developer Tools','developer-tools','Code hosting, deployment, APIs and debugging.','terminal',5),
('Marketing','marketing','Email marketing, SEO, social scheduling and analytics.','megaphone',6),
('Business','business','CRM, ecommerce and company-wide software suites.','briefcase',7),
('Finance','finance','Payments, accounting and money transfer.','credit-card',8),
('Travel','travel','Flights, hotels and stays.','plane',9),
('Design','design','Graphics, interface design and photo editing.','palette',10),
('Productivity','productivity','Notes, tasks and project management.','check-square',11),
('Hosting & Cloud','hosting-cloud','Cloud infrastructure, hosting and CDN.','server',12),
('Communication','communication','Team chat, video calls and messaging.','message-circle',13),
('Entertainment','entertainment','Streaming video and music.','play-circle',14),
('Health & Wellness','health-wellness','Fitness tracking, meditation and healthcare.','heart-pulse',15),
('Freelancing','freelancing','Find freelance work or hire freelancers.','users',16);

INSERT INTO public.services
 (name, slug, description, long_description, official_url, category_id, subcategory, pricing_type, price_description, has_free_plan, has_free_trial, platforms, availability, founded_year, features, best_for, tags)
SELECT v.name, v.slug, v.description, v.long_description, v.official_url, c.id, v.subcategory, v.pricing_type, v.price_description,
       v.has_free_plan, v.has_free_trial, v.platforms, v.availability, v.founded_year, v.features, v.best_for, v.tags
FROM (VALUES
-- AI TOOLS
('ai-tools','ChatGPT','chatgpt','AI chat assistant from OpenAI for writing, coding, analysis and everyday questions.','ChatGPT is a conversational AI assistant built on OpenAI models. It handles text generation, summarisation, coding help, data analysis and image generation, with a free tier and paid plans that unlock more capable models and higher limits.','https://chat.openai.com','AI chat assistant','freemium','Free tier available; paid plans listed on the official pricing page.',true,false,ARRAY['Web','Android','iOS','macOS','Windows','API'],'Global',2022,ARRAY['Conversational AI chat','Code generation and debugging','File and image understanding','Image generation','Custom GPTs'],ARRAY['Students','Developers','Professionals'],ARRAY['ai','chatbot','ai writing','coding assistant']),
('ai-tools','Claude','claude','AI assistant from Anthropic focused on long-form writing, reasoning and coding.','Claude is Anthropic''s AI assistant. It is commonly used for long document analysis, writing, and software development, and supports large context inputs plus an API for developers.','https://claude.ai','AI chat assistant','freemium','Free tier available; paid plans listed on the official pricing page.',true,false,ARRAY['Web','Android','iOS','macOS','API'],'Available in many countries',2023,ARRAY['Long-context document analysis','Writing and editing','Code generation','Projects and file uploads','Developer API'],ARRAY['Developers','Professionals','Researchers'],ARRAY['ai','chatbot','ai writing','llm']),
('ai-tools','Gemini','gemini','Google''s AI assistant for writing, research and image generation, integrated with Google apps.','Gemini is Google''s AI assistant, available on the web and mobile and integrated with Google Workspace apps. It supports text, image and file inputs and has developer access through the Gemini API.','https://gemini.google.com','AI chat assistant','freemium','Free tier available; paid plans listed on the official pricing page.',true,false,ARRAY['Web','Android','iOS','API'],'Available in many countries',2023,ARRAY['Conversational AI chat','Image generation','Google Workspace integration','File and image input','Developer API'],ARRAY['Students','Professionals','Developers'],ARRAY['ai','chatbot','google','ai writing']),
('ai-tools','Perplexity','perplexity','AI answer engine that searches the web and cites its sources.','Perplexity answers questions by searching the web and returning summarised answers with links to sources, which makes it useful for research where traceability matters.','https://www.perplexity.ai','AI search','freemium','Free tier available; paid plans listed on the official pricing page.',true,false,ARRAY['Web','Android','iOS','API'],'Global',2022,ARRAY['Cited web answers','Follow-up questions','File upload','Focused search modes'],ARRAY['Students','Researchers','Professionals'],ARRAY['ai','ai search','research','answers']),
('ai-tools','Grammarly','grammarly','Writing assistant that checks grammar, clarity and tone across apps and browsers.','Grammarly reviews text for grammar, spelling, clarity and tone, and offers AI writing suggestions. It works as a browser extension, desktop app and keyboard.','https://www.grammarly.com','Writing assistant','freemium','Free tier available; paid plans listed on the official pricing page.',true,false,ARRAY['Web','Windows','macOS','Android','iOS'],'Global',2009,ARRAY['Grammar and spelling checks','Tone and clarity suggestions','AI writing generation','Browser extension','Plagiarism checking on paid plans'],ARRAY['Students','Professionals','Writers'],ARRAY['ai writing','grammar','proofreading','editing']),
('ai-tools','Midjourney','midjourney','AI image generation service known for stylised, high-detail images.','Midjourney generates images from text prompts. It is used through its web app and Discord, and is aimed at illustration, concept art and stylised visuals.','https://www.midjourney.com','AI image generator','paid','Subscription pricing listed on the official pricing page.',false,false,ARRAY['Web'],'Global',2022,ARRAY['Text-to-image generation','Image variations and upscaling','Style references','Web and Discord interfaces'],ARRAY['Designers','Artists','Marketers'],ARRAY['ai image generator','image generation','art','design']),
('ai-tools','ElevenLabs','elevenlabs','AI text-to-speech and voice cloning for narration, dubbing and apps.','ElevenLabs provides AI speech synthesis with a large voice library, multi-language support, dubbing tools and an API for developers building voice features.','https://elevenlabs.io','AI audio','freemium','Free tier available; paid plans listed on the official pricing page.',true,false,ARRAY['Web','API'],'Global',2022,ARRAY['Text-to-speech','Voice cloning','Multi-language dubbing','Speech-to-text','Developer API'],ARRAY['Creators','Developers','Businesses'],ARRAY['ai','text to speech','voice','audio']),
('ai-tools','GitHub Copilot','github-copilot','AI coding assistant that suggests code and answers questions inside your editor.','GitHub Copilot suggests code completions and whole functions inside editors such as VS Code and JetBrains IDEs, and includes a chat interface for explaining or refactoring code.','https://github.com/features/copilot','AI coding assistant','freemium','Free tier available with limits; paid plans listed on the official pricing page.',true,true,ARRAY['Windows','macOS','Linux','Web'],'Global',2021,ARRAY['Inline code completion','Chat about your codebase','Pull request summaries','Editor and IDE integrations'],ARRAY['Developers','Students','Engineering teams'],ARRAY['ai','coding assistant','developer tools','code completion']),
-- WEBSITE BUILDERS
('website-builders','Wix','wix','Drag-and-drop website builder with templates, hosting and ecommerce built in.','Wix is a hosted website builder aimed at users without coding experience. It includes templates, a drag-and-drop editor, hosting, domains, ecommerce and booking features.','https://www.wix.com','No-code website builder','freemium','Free plan with Wix branding; paid plans listed on the official pricing page.',true,false,ARRAY['Web','Android','iOS'],'Global',2006,ARRAY['Drag-and-drop editor','Hundreds of templates','Hosting and domains included','Online store','Appointment booking','App market'],ARRAY['Beginners','Small businesses','Freelancers'],ARRAY['website builder','no-code','cms','ecommerce']),
('website-builders','Webflow','webflow','Visual website builder that produces production-grade sites with a built-in CMS.','Webflow lets designers build responsive sites visually with precise control over layout and styling, and includes a CMS, hosting and ecommerce. It has a steeper learning curve than simpler builders.','https://webflow.com','Visual development','freemium','Free starter plan; paid site and workspace plans on the official pricing page.',true,false,ARRAY['Web'],'Global',2013,ARRAY['Visual CSS-level design control','Built-in CMS','Responsive breakpoints','Hosting on Webflow cloud','Interactions and animations'],ARRAY['Designers','Agencies','Marketing teams'],ARRAY['website builder','no-code','cms','design']),
('website-builders','Framer','framer','Design-led website builder with a canvas editor, CMS and instant publishing.','Framer combines a design-tool canvas with website publishing. It supports responsive layouts, a CMS, animations and custom code components, and publishes to its own hosting.','https://www.framer.com','Visual website builder','freemium','Free plan available; paid site plans listed on the official pricing page.',true,false,ARRAY['Web'],'Global',2014,ARRAY['Canvas-based visual editor','CMS collections','Animations and effects','Custom React code components','One-click publishing'],ARRAY['Designers','Startups','Freelancers'],ARRAY['website builder','no-code','design','landing pages']),
('website-builders','Squarespace','squarespace','Template-driven website builder for portfolios, stores and business sites.','Squarespace offers designed templates with an editor, hosting, domains, ecommerce, scheduling and email marketing in one subscription.','https://www.squarespace.com','No-code website builder','paid','Subscription plans with a trial period; see the official pricing page.',false,true,ARRAY['Web','iOS','Android'],'Global',2003,ARRAY['Designer templates','Hosting and domains','Online store','Scheduling','Email campaigns'],ARRAY['Creatives','Small businesses','Portfolios'],ARRAY['website builder','portfolio','ecommerce','templates']),
('website-builders','WordPress.com','wordpress-com','Hosted WordPress for blogs, publications and business sites.','WordPress.com is the hosted version of WordPress, run by Automattic. It handles hosting and updates, with plugin and theme support on higher plans.','https://wordpress.com','CMS hosting','freemium','Free plan with limits; paid plans listed on the official pricing page.',true,false,ARRAY['Web','Android','iOS'],'Global',2005,ARRAY['Block-based editor','Themes and plugins on paid plans','Managed hosting','Custom domains','Built-in SEO tools'],ARRAY['Bloggers','Publishers','Small businesses'],ARRAY['website builder','cms','blogging','wordpress']),
('website-builders','Shopify','shopify','Hosted ecommerce platform for building and running online stores.','Shopify provides storefront themes, product and inventory management, checkout, payments and an app ecosystem for online and in-person selling.','https://www.shopify.com','Ecommerce platform','paid','Subscription plans with a trial period; see the official pricing page.',false,true,ARRAY['Web','Android','iOS','API'],'Global',2006,ARRAY['Storefront themes','Product and inventory management','Checkout and payments','App store','Point of sale'],ARRAY['Small businesses','Retailers','Startups'],ARRAY['ecommerce','online store','website builder','payments']),
-- EDUCATION
('education','Coursera','coursera','Courses, certificates and degrees from universities and companies.','Coursera hosts courses, professional certificates and full degree programmes from universities and companies. Many courses can be audited free, with payment for graded assignments and certificates.','https://www.coursera.org','Online courses','freemium','Free auditing on many courses; subscriptions and paid certificates on the official pricing page.',true,true,ARRAY['Web','Android','iOS'],'Global',2012,ARRAY['University-backed courses','Professional certificates','Online degrees','Graded assignments','Mobile offline viewing'],ARRAY['Students','Professionals','Career switchers'],ARRAY['online learning','courses','certificates','learn python']),
('education','Udemy','udemy','Marketplace of practical, instructor-created video courses.','Udemy is a course marketplace where independent instructors publish video courses on programming, business, design and other topics. Courses are usually bought individually with lifetime access.','https://www.udemy.com','Online courses','paid','Individual course purchases; business subscriptions available.',false,false,ARRAY['Web','Android','iOS'],'Global',2010,ARRAY['Individual course purchase','Lifetime access to bought courses','Video lectures and exercises','Downloadable resources','Certificates of completion'],ARRAY['Beginners','Developers','Professionals'],ARRAY['online learning','courses','learn python','video courses']),
('education','edX','edx','University-level courses and programmes, including audit-free options.','edX, founded by MIT and Harvard and now part of 2U, offers university courses, MicroMasters programmes and degrees, with audit access on many courses.','https://www.edx.org','Online courses','freemium','Free auditing on many courses; paid certificates and programmes.',true,false,ARRAY['Web','Android','iOS'],'Global',2012,ARRAY['University courses','MicroMasters and professional certificates','Audit track','Graded assessments'],ARRAY['Students','Researchers','Professionals'],ARRAY['online learning','courses','university','certificates']),
('education','freeCodeCamp','freecodecamp','Free, project-based curriculum for web development and programming.','freeCodeCamp is a non-profit offering a free curriculum covering web development, JavaScript, Python, data analysis and certifications, built around coding projects in the browser.','https://www.freecodecamp.org','Coding curriculum','free','Free to use; funded by donations.',true,false,ARRAY['Web'],'Global',2014,ARRAY['Interactive coding lessons','Project-based certifications','Python and JavaScript tracks','Community forum','No cost'],ARRAY['Beginners','Self-taught developers','Students'],ARRAY['learn python','coding','web development','free courses']),
('education','DataCamp','datacamp','Interactive courses for data analysis, Python, R and SQL.','DataCamp teaches data skills through short interactive exercises in the browser, covering Python, R, SQL, data visualisation and machine learning, with skill tracks and projects.','https://www.datacamp.com','Data learning','freemium','Limited free content; subscriptions on the official pricing page.',true,true,ARRAY['Web','Android','iOS'],'Global',2013,ARRAY['In-browser coding exercises','Python, R and SQL tracks','Guided projects','Skill assessments','Certifications'],ARRAY['Students','Analysts','Career switchers'],ARRAY['learn python','data science','sql','online learning']),
('education','Khan Academy','khan-academy','Free lessons and practice in maths, science and more.','Khan Academy is a non-profit providing free video lessons and practice exercises across maths, science, economics and test preparation, for school and university level learners.','https://www.khanacademy.org','School learning','free','Free to use; funded by donations.',true,false,ARRAY['Web','Android','iOS'],'Global',2008,ARRAY['Video lessons','Practice exercises with hints','Progress tracking','Test preparation content'],ARRAY['Students','Parents','Teachers'],ARRAY['online learning','maths','science','free courses']),
('education','Duolingo','duolingo','Gamified language learning through short daily lessons.','Duolingo teaches languages using short exercises, streaks and spaced repetition, with a free ad-supported tier and a paid subscription that removes ads and adds features.','https://www.duolingo.com','Language learning','freemium','Free with ads; Super subscription on the official pricing page.',true,true,ARRAY['Web','Android','iOS'],'Global',2011,ARRAY['Short gamified lessons','Dozens of languages','Streaks and progress tracking','Speaking and listening practice'],ARRAY['Beginners','Students','Travellers'],ARRAY['learn language','education','duolingo','self study']),
('education','LeetCode','leetcode','Coding practice problems and contests for interview preparation.','LeetCode hosts programming problems organised by topic and difficulty, with contests, discussion solutions and company-focused study plans used widely for technical interview preparation.','https://leetcode.com','Coding practice','freemium','Free problem access; premium subscription on the official pricing page.',true,false,ARRAY['Web'],'Global',2015,ARRAY['Thousands of coding problems','Online judge in many languages','Contests','Study plans','Discussion solutions'],ARRAY['Developers','Students','Job seekers'],ARRAY['coding practice','interview prep','algorithms','learn python']),
-- DELIVERY & SHOPPING
('delivery-shopping','Amazon','amazon','Global online marketplace for products, with fast delivery options.','Amazon is an online marketplace selling products across most retail categories, with first-party and third-party sellers, a paid Prime membership offering faster shipping, and grocery delivery in some regions.','https://www.amazon.com','Online marketplace','free','Free to browse and buy; Prime membership is a paid subscription.',true,true,ARRAY['Web','Android','iOS'],'Global',1994,ARRAY['Large product catalogue','Third-party marketplace','Prime delivery options','Returns and refunds','Grocery delivery in select regions'],ARRAY['General internet users','Households','Small businesses'],ARRAY['shopping','ecommerce','delivery','marketplace']),
('delivery-shopping','Blinkit','blinkit','Quick-commerce grocery delivery in India, operated by Zomato.','Blinkit delivers groceries and household essentials from local dark stores in Indian cities, focusing on very short delivery windows.','https://blinkit.com','Grocery delivery','free','No subscription required; delivery and handling fees may apply.',true,false,ARRAY['Web','Android','iOS'],'India',2013,ARRAY['Quick grocery delivery','Household essentials','Local store inventory','Order tracking'],ARRAY['Households','Urban users'],ARRAY['grocery delivery','quick commerce','india','groceries']),
('delivery-shopping','Zepto','zepto','Quick grocery and essentials delivery across Indian cities.','Zepto is an Indian quick-commerce app delivering groceries, fresh produce and daily essentials from nearby micro-warehouses.','https://www.zeptonow.com','Grocery delivery','free','No subscription required; delivery fees may apply. Paid membership available.',true,false,ARRAY['Web','Android','iOS'],'India',2021,ARRAY['Quick grocery delivery','Fresh produce','Daily essentials','Order tracking'],ARRAY['Households','Urban users'],ARRAY['grocery delivery','quick commerce','india','groceries']),
('delivery-shopping','BigBasket','bigbasket','Online grocery supermarket in India with scheduled and express delivery.','BigBasket, part of the Tata group, sells groceries, fresh produce, packaged food and household goods online with scheduled slots and quicker express options in some areas.','https://www.bigbasket.com','Grocery delivery','free','No subscription required; membership option available.',true,false,ARRAY['Web','Android','iOS'],'India',2011,ARRAY['Wide grocery catalogue','Scheduled delivery slots','Express delivery in select areas','Own-brand products'],ARRAY['Households','Families'],ARRAY['grocery delivery','groceries','india','supermarket']),
('delivery-shopping','Swiggy Instamart','swiggy-instamart','Grocery and essentials delivery inside the Swiggy app.','Swiggy Instamart is Swiggy''s quick grocery service, delivering everyday items from local stores through the Swiggy app.','https://www.swiggy.com/instamart','Grocery delivery','free','No subscription required; delivery fees may apply.',true,false,ARRAY['Web','Android','iOS'],'India',2020,ARRAY['Quick grocery delivery','Integrated with Swiggy food orders','Live order tracking'],ARRAY['Households','Urban users'],ARRAY['grocery delivery','quick commerce','india','groceries']),
('delivery-shopping','Swiggy','swiggy','Food delivery from restaurants across India.','Swiggy is an Indian food delivery platform connecting users with local restaurants, with live tracking, and adjacent services for groceries and dining out.','https://www.swiggy.com','Food delivery','free','Free to order; delivery fees and paid membership available.',true,false,ARRAY['Web','Android','iOS'],'India',2014,ARRAY['Restaurant food delivery','Live order tracking','Dining out offers','Membership discounts'],ARRAY['General internet users','Urban users'],ARRAY['food delivery','restaurants','india','delivery']),
('delivery-shopping','Zomato','zomato','Restaurant discovery and food delivery in India.','Zomato offers restaurant listings, menus and food delivery, plus dining-out reservations and offers.','https://www.zomato.com','Food delivery','free','Free to order; delivery fees and paid membership available.',true,false,ARRAY['Web','Android','iOS'],'India',2008,ARRAY['Food delivery','Restaurant discovery and menus','Dining reservations','Order tracking'],ARRAY['General internet users','Urban users'],ARRAY['food delivery','restaurants','india','delivery']),
('delivery-shopping','DoorDash','doordash','Food and retail delivery marketplace in the United States and other markets.','DoorDash delivers restaurant meals, groceries and retail items through local couriers, with a paid DashPass subscription for reduced fees.','https://www.doordash.com','Food delivery','free','Free to order; delivery fees and DashPass subscription available.',true,true,ARRAY['Web','Android','iOS'],'United States, Canada, Australia and other markets',2013,ARRAY['Restaurant delivery','Grocery and retail delivery','Scheduled orders','Subscription for reduced fees'],ARRAY['General internet users','Households'],ARRAY['food delivery','grocery delivery','delivery','usa']),
('delivery-shopping','Instacart','instacart','Grocery delivery and pickup from local supermarkets in North America.','Instacart lets users shop from partner supermarkets and have orders delivered or prepared for pickup by shoppers, with an optional membership for lower fees.','https://www.instacart.com','Grocery delivery','free','Free to order; delivery fees and Instacart+ membership available.',true,true,ARRAY['Web','Android','iOS'],'United States and Canada',2012,ARRAY['Delivery from partner supermarkets','Pickup orders','Same-day slots','Membership for reduced fees'],ARRAY['Households','Families'],ARRAY['grocery delivery','groceries','delivery','usa']),
-- DEVELOPER TOOLS
('developer-tools','GitHub','github','Git hosting with pull requests, issues, CI and code review.','GitHub hosts Git repositories and adds collaboration around them: pull requests, code review, issues, project boards, Actions for CI/CD, packages and security scanning.','https://github.com','Code hosting','freemium','Free plan for public and private repos; paid plans on the official pricing page.',true,true,ARRAY['Web','Windows','macOS','Linux','Android','iOS','API'],'Global',2008,ARRAY['Git repository hosting','Pull requests and code review','Issues and projects','GitHub Actions CI/CD','Packages and releases','REST and GraphQL APIs'],ARRAY['Developers','Engineering teams','Students'],ARRAY['git','code hosting','ci cd','developer tools']),
('developer-tools','GitLab','gitlab','Git hosting with built-in CI/CD, issue tracking and DevOps features.','GitLab is a DevOps platform combining Git repositories, CI/CD pipelines, issue tracking, container registry and security scanning, available as SaaS or self-hosted.','https://about.gitlab.com','Code hosting','freemium','Free tier available; paid tiers on the official pricing page.',true,true,ARRAY['Web','Linux','API'],'Global',2011,ARRAY['Git repository hosting','Built-in CI/CD pipelines','Issue boards','Container registry','Self-hosted option'],ARRAY['Developers','Engineering teams','Enterprises'],ARRAY['git','code hosting','ci cd','devops']),
('developer-tools','Vercel','vercel','Deployment platform for frontend frameworks with preview deployments.','Vercel hosts frontend applications and serverless functions, with Git-connected deployments, per-branch previews, edge network delivery and first-class Next.js support.','https://vercel.com','Frontend hosting','freemium','Free hobby plan; paid plans on the official pricing page.',true,true,ARRAY['Web','API'],'Global',2015,ARRAY['Git-connected deployments','Preview deployments per branch','Serverless and edge functions','Global CDN','Custom domains and SSL'],ARRAY['Developers','Startups','Frontend teams'],ARRAY['hosting','deployment','frontend','developer tools']),
('developer-tools','Netlify','netlify','Hosting and deployment for web frontends with build automation.','Netlify builds and deploys web projects from Git, providing a global CDN, serverless functions, form handling, redirects and deploy previews.','https://www.netlify.com','Frontend hosting','freemium','Free plan; paid plans on the official pricing page.',true,true,ARRAY['Web','API'],'Global',2014,ARRAY['Continuous deployment from Git','Deploy previews','Serverless functions','Global CDN','Form handling'],ARRAY['Developers','Startups','Agencies'],ARRAY['hosting','deployment','frontend','jamstack']),
('developer-tools','Postman','postman','API client for building, testing and documenting APIs.','Postman is used to send API requests, organise them into collections, write tests, mock endpoints and publish documentation, with team workspaces for collaboration.','https://www.postman.com','API tooling','freemium','Free plan; paid plans on the official pricing page.',true,true,ARRAY['Web','Windows','macOS','Linux','API'],'Global',2012,ARRAY['API request builder','Collections and environments','Automated API tests','Mock servers','API documentation'],ARRAY['Developers','QA engineers','API teams'],ARRAY['api','testing','developer tools','rest']),
('developer-tools','Docker','docker','Container tooling for building and running applications consistently.','Docker packages applications and dependencies into containers. Docker Desktop provides local container tooling, and Docker Hub hosts container images.','https://www.docker.com','Containers','freemium','Free tier for personal use; paid subscriptions on the official pricing page.',true,false,ARRAY['Windows','macOS','Linux','Web'],'Global',2013,ARRAY['Container build and run','Docker Compose for multi-service apps','Image registry','Local development environments'],ARRAY['Developers','DevOps engineers','Engineering teams'],ARRAY['containers','devops','developer tools','deployment']),
('developer-tools','Visual Studio Code','visual-studio-code','Free code editor with extensions, debugging and Git integration.','Visual Studio Code is a free, cross-platform source code editor from Microsoft with an extension marketplace, integrated terminal, debugging and Git support.','https://code.visualstudio.com','Code editor','free','Free download.',true,false,ARRAY['Windows','macOS','Linux','Web'],'Global',2015,ARRAY['Extension marketplace','Integrated debugger','Built-in Git support','Integrated terminal','Remote development'],ARRAY['Developers','Students','Engineering teams'],ARRAY['code editor','ide','developer tools','programming']),
('developer-tools','Sentry','sentry','Error monitoring and performance tracing for applications.','Sentry captures application errors and performance data with stack traces, release tracking and alerting across many languages and frameworks.','https://sentry.io','Monitoring','freemium','Free developer tier; paid plans on the official pricing page.',true,true,ARRAY['Web','API'],'Global',2012,ARRAY['Error tracking with stack traces','Performance tracing','Release health','Alerting integrations','SDKs for many languages'],ARRAY['Developers','Engineering teams','Startups'],ARRAY['monitoring','error tracking','observability','developer tools']),
('developer-tools','Supabase','supabase','Open-source backend with Postgres database, auth, storage and APIs.','Supabase provides a hosted Postgres database with auto-generated APIs, authentication, file storage, edge functions and realtime subscriptions, and can also be self-hosted.','https://supabase.com','Backend platform','freemium','Free tier; paid plans on the official pricing page.',true,false,ARRAY['Web','API'],'Global',2020,ARRAY['Managed Postgres database','Authentication','File storage','Realtime subscriptions','Edge functions','Auto-generated REST APIs'],ARRAY['Developers','Startups','Indie makers'],ARRAY['backend','database','auth','developer tools']),
-- HOSTING & CLOUD
('hosting-cloud','Amazon Web Services','aws','Broad cloud platform covering compute, storage, databases and networking.','AWS is Amazon''s cloud platform, offering a very wide range of infrastructure and managed services including EC2 compute, S3 storage, RDS databases, Lambda functions and networking, billed by usage.','https://aws.amazon.com','Cloud platform','paid','Usage-based pricing with a limited free tier; see the official pricing page.',true,true,ARRAY['Web','API'],'Global',2006,ARRAY['Virtual machines (EC2)','Object storage (S3)','Managed databases','Serverless functions (Lambda)','Global regions and CDN','Identity and access management'],ARRAY['Developers','Enterprises','Startups'],ARRAY['cloud hosting','infrastructure','servers','devops']),
('hosting-cloud','Microsoft Azure','microsoft-azure','Microsoft''s cloud platform for infrastructure, data and enterprise workloads.','Azure provides compute, storage, databases, AI services and identity, with strong integration into Microsoft enterprise tooling such as Entra ID and Windows Server workloads.','https://azure.microsoft.com','Cloud platform','paid','Usage-based pricing with a limited free tier; see the official pricing page.',true,true,ARRAY['Web','API'],'Global',2010,ARRAY['Virtual machines','Managed SQL and NoSQL databases','App Service hosting','Azure Functions','Entra ID integration','AI and ML services'],ARRAY['Enterprises','Developers','IT teams'],ARRAY['cloud hosting','infrastructure','microsoft','devops']),
('hosting-cloud','Google Cloud','google-cloud','Google''s cloud platform with compute, data analytics and AI services.','Google Cloud offers compute, Kubernetes, BigQuery analytics, managed databases and AI services on Google''s network infrastructure.','https://cloud.google.com','Cloud platform','paid','Usage-based pricing with a limited free tier; see the official pricing page.',true,true,ARRAY['Web','API'],'Global',2008,ARRAY['Compute Engine virtual machines','Google Kubernetes Engine','BigQuery analytics','Cloud Run and Cloud Functions','Managed databases','AI and ML APIs'],ARRAY['Developers','Data teams','Enterprises'],ARRAY['cloud hosting','infrastructure','kubernetes','analytics']),
('hosting-cloud','DigitalOcean','digitalocean','Cloud hosting with simple virtual servers, managed databases and app hosting.','DigitalOcean focuses on straightforward cloud infrastructure: Droplet virtual machines, managed databases, Kubernetes, object storage and App Platform for deploying apps from Git.','https://www.digitalocean.com','Cloud hosting','paid','Usage-based pricing; see the official pricing page.',false,false,ARRAY['Web','API'],'Global',2011,ARRAY['Droplet virtual machines','Managed databases','Kubernetes','Spaces object storage','App Platform deployments','Predictable pricing'],ARRAY['Developers','Startups','Small businesses'],ARRAY['cloud hosting','vps','servers','infrastructure']),
('hosting-cloud','Cloudflare','cloudflare','CDN, DNS, security and edge compute in front of your sites and apps.','Cloudflare provides DNS, CDN caching, DDoS protection, WAF, Zero Trust access and edge compute with Workers, plus Pages hosting and R2 object storage.','https://www.cloudflare.com','CDN and edge','freemium','Free plan; paid plans on the official pricing page.',true,false,ARRAY['Web','API'],'Global',2009,ARRAY['Global CDN and caching','DNS management','DDoS protection and WAF','Workers edge functions','Pages static hosting','R2 object storage'],ARRAY['Developers','Businesses','Enterprises'],ARRAY['cdn','dns','security','edge hosting']),
('hosting-cloud','Railway','railway','Deploy apps, databases and services from Git with minimal configuration.','Railway hosts applications and databases with Git-based deployments, environment management and usage-based pricing, aimed at reducing infrastructure setup.','https://railway.com','App hosting','paid','Usage-based pricing with trial credits; see the official pricing page.',false,true,ARRAY['Web','API'],'Global',2020,ARRAY['Git-based deployments','Managed Postgres, MySQL and Redis','Environment variables and secrets','Usage-based billing','Logs and metrics'],ARRAY['Developers','Startups','Indie makers'],ARRAY['hosting','deployment','paas','developer tools']),
-- MARKETING
('marketing','Mailchimp','mailchimp','Email marketing platform with campaigns, automations and audience management.','Mailchimp provides email campaign design, list segmentation, automation journeys, landing pages and reporting, with a limited free tier for small lists.','https://mailchimp.com','Email marketing','freemium','Limited free plan; paid plans scale with contacts. See the official pricing page.',true,true,ARRAY['Web','Android','iOS','API'],'Global',2001,ARRAY['Drag-and-drop email builder','Audience segmentation','Automation journeys','Landing pages and forms','Campaign reporting','A/B testing'],ARRAY['Small businesses','Marketers','Creators'],ARRAY['email marketing','newsletter','automation','marketing']),
('marketing','HubSpot','hubspot','CRM with marketing, sales and service tools including email marketing.','HubSpot combines a free CRM with paid marketing, sales, service and CMS hubs covering email marketing, forms, landing pages, pipelines and reporting.','https://www.hubspot.com','CRM and marketing','freemium','Free CRM tools; paid hubs on the official pricing page.',true,true,ARRAY['Web','Android','iOS','API'],'Global',2006,ARRAY['Contact CRM','Email marketing and automation','Landing pages and forms','Sales pipelines','Reporting dashboards','Live chat'],ARRAY['Small businesses','Sales teams','Marketers'],ARRAY['crm','email marketing','marketing automation','sales']),
('marketing','Brevo','brevo','Email, SMS and marketing automation platform (formerly Sendinblue).','Brevo offers email campaigns, transactional email, SMS, chat and a CRM, with pricing based on emails sent rather than contact count on many plans.','https://www.brevo.com','Email marketing','freemium','Free plan with daily sending limits; paid plans on the official pricing page.',true,false,ARRAY['Web','Android','iOS','API'],'Global',2012,ARRAY['Email campaigns','Transactional email API','SMS campaigns','Marketing automation','Built-in CRM','Landing pages'],ARRAY['Small businesses','Startups','Marketers'],ARRAY['email marketing','sms','automation','transactional email']),
('marketing','Semrush','semrush','SEO and competitive research suite for keywords, backlinks and site audits.','Semrush provides keyword research, rank tracking, backlink analysis, site audits, competitor comparison and advertising research for search marketing teams.','https://www.semrush.com','SEO','paid','Subscription plans with a trial; see the official pricing page.',false,true,ARRAY['Web','API'],'Global',2008,ARRAY['Keyword research','Competitor analysis','Backlink audit','Site technical audit','Rank tracking','Content optimisation tools'],ARRAY['Marketers','Agencies','SEO specialists'],ARRAY['seo','keyword research','marketing','analytics']),
('marketing','Ahrefs','ahrefs','SEO toolset focused on backlinks, keywords and site audits.','Ahrefs offers a large backlink index, keyword research, rank tracking, content exploration and technical site audits, with a limited free tier for verified site owners.','https://ahrefs.com','SEO','paid','Subscription plans; limited free tools available. See the official pricing page.',true,false,ARRAY['Web','API'],'Global',2010,ARRAY['Backlink index and analysis','Keyword explorer','Site audit','Rank tracker','Content explorer'],ARRAY['Marketers','Agencies','SEO specialists'],ARRAY['seo','backlinks','keyword research','marketing']),
('marketing','Buffer','buffer','Schedule and publish social media posts across multiple channels.','Buffer schedules posts to social networks, offers a content calendar, basic analytics and engagement tools, with a free tier for a small number of channels.','https://buffer.com','Social media','freemium','Free plan for limited channels; paid plans on the official pricing page.',true,true,ARRAY['Web','Android','iOS','API'],'Global',2010,ARRAY['Post scheduling','Content calendar','Multi-channel publishing','Basic analytics','Team collaboration'],ARRAY['Creators','Small businesses','Marketers'],ARRAY['social media','scheduling','marketing','content']),
('marketing','Google Analytics','google-analytics','Website and app analytics for traffic, acquisition and conversions.','Google Analytics (GA4) measures website and app usage with event-based tracking, audience reports, acquisition channels, conversions and integrations with Google Ads and BigQuery.','https://marketingplatform.google.com/about/analytics/','Analytics','freemium','Free for most use; Analytics 360 is a paid enterprise tier.',true,false,ARRAY['Web','Android','iOS','API'],'Global',2005,ARRAY['Event-based tracking','Acquisition and traffic reports','Conversion tracking','Audience segmentation','Google Ads integration','BigQuery export'],ARRAY['Marketers','Small businesses','Product teams'],ARRAY['analytics','tracking','marketing','reporting']),
-- BUSINESS
('business','Salesforce','salesforce','Enterprise CRM platform for sales, service and marketing.','Salesforce provides customer relationship management across sales, service, marketing and analytics, with heavy customisation, automation and an app marketplace.','https://www.salesforce.com','CRM','paid','Per-user subscription plans with trials; see the official pricing page.',false,true,ARRAY['Web','Android','iOS','API'],'Global',1999,ARRAY['Sales pipeline management','Case and service management','Workflow automation','Custom objects and fields','Reports and dashboards','AppExchange integrations'],ARRAY['Enterprises','Sales teams','Large businesses'],ARRAY['crm','sales','enterprise','business software']),
('business','Zoho CRM','zoho-crm','CRM for sales pipelines, automation and reporting, part of the Zoho suite.','Zoho CRM manages leads, contacts, deals and workflows, and integrates with the wider Zoho suite of business apps. It offers lower-cost tiers than most enterprise CRMs.','https://www.zoho.com/crm/','CRM','freemium','Free tier for a small number of users; paid plans on the official pricing page.',true,true,ARRAY['Web','Android','iOS','API'],'Global',2005,ARRAY['Lead and deal management','Workflow automation','Email integration','Reports and dashboards','Zoho suite integrations'],ARRAY['Small businesses','Sales teams','Startups'],ARRAY['crm','sales','business software','automation']),
('business','Google Workspace','google-workspace','Business email, docs, storage and meetings on a custom domain.','Google Workspace bundles Gmail on your own domain with Docs, Sheets, Slides, Drive storage, Calendar and Meet, plus admin controls for organisations.','https://workspace.google.com','Office suite','paid','Per-user subscription plans with a trial; see the official pricing page.',false,true,ARRAY['Web','Android','iOS','Windows','macOS','API'],'Global',2006,ARRAY['Custom-domain email','Docs, Sheets and Slides','Drive cloud storage','Calendar and Meet','Admin console and security controls'],ARRAY['Small businesses','Startups','Enterprises'],ARRAY['email','office suite','collaboration','business software']),
-- FINANCE
('finance','Stripe','stripe','Developer-focused payments infrastructure for online businesses.','Stripe processes online payments with APIs and hosted checkout, and adds subscriptions, invoicing, fraud prevention, payouts and reporting for internet businesses.','https://stripe.com','Payments','paid','Per-transaction fees; see the official pricing page.',false,false,ARRAY['Web','API','Android','iOS'],'Available in many countries',2010,ARRAY['Card and wallet payments','Hosted checkout and payment links','Subscription billing','Invoicing','Fraud prevention','Developer APIs and SDKs'],ARRAY['Developers','Startups','Online businesses'],ARRAY['payments','payment gateway','billing','finance']),
('finance','Razorpay','razorpay','Payment gateway and business banking for Indian businesses.','Razorpay offers online payment collection for Indian businesses including UPI, cards and netbanking, plus payment links, subscriptions, payouts and settlement tooling.','https://razorpay.com','Payments','paid','Per-transaction fees; see the official pricing page.',false,false,ARRAY['Web','API','Android','iOS'],'India',2014,ARRAY['UPI, cards and netbanking','Payment links and pages','Subscriptions','Payouts','Settlement dashboard','Developer APIs'],ARRAY['Small businesses','Startups','Developers'],ARRAY['payments','payment gateway','upi','india']),
('finance','PayPal','paypal','Online payments and money transfer for individuals and businesses.','PayPal supports online purchases, invoicing, business checkout and cross-border transfers, with buyer and seller protection programmes.','https://www.paypal.com','Payments','freemium','Free personal accounts; transaction fees apply to business and cross-border payments.',true,false,ARRAY['Web','Android','iOS','API'],'Available in many countries',1998,ARRAY['Online checkout','Send and request money','Invoicing','Cross-border payments','Buyer and seller protection'],ARRAY['Freelancers','Small businesses','General internet users'],ARRAY['payments','money transfer','invoicing','finance']),
('finance','QuickBooks','quickbooks','Accounting software for invoicing, expenses and tax reporting.','QuickBooks from Intuit handles bookkeeping for small businesses: invoicing, expense tracking, bank reconciliation, payroll add-ons and tax reporting.','https://quickbooks.intuit.com','Accounting','paid','Subscription plans with a trial; see the official pricing page.',false,true,ARRAY['Web','Android','iOS'],'Available in many countries',1983,ARRAY['Invoicing','Expense tracking','Bank reconciliation','Financial reports','Payroll add-ons'],ARRAY['Small businesses','Freelancers','Accountants'],ARRAY['accounting','invoicing','bookkeeping','finance']),
('finance','Wise','wise','International money transfers and multi-currency accounts.','Wise offers cross-border transfers using mid-market exchange rates with upfront fees, plus multi-currency accounts and debit cards for personal and business use.','https://wise.com','Money transfer','paid','Transfer fees shown upfront per transaction; see the official pricing page.',true,false,ARRAY['Web','Android','iOS','API'],'Available in many countries',2011,ARRAY['International transfers','Multi-currency account','Debit card','Upfront fee display','Business accounts'],ARRAY['Freelancers','Travellers','Small businesses'],ARRAY['money transfer','currency','banking','finance']),
-- DESIGN
('design','Canva','canva','Template-based design tool for graphics, presentations and social posts.','Canva is a browser-based design tool with templates for social media, presentations, documents, video and print, plus brand kits and AI editing features on paid plans.','https://www.canva.com','Graphic design','freemium','Free plan; Canva Pro and Teams on the official pricing page.',true,true,ARRAY['Web','Android','iOS','Windows','macOS'],'Global',2013,ARRAY['Template library','Drag-and-drop editor','Brand kits','Presentations and video editing','Background remover on paid plans','Team collaboration'],ARRAY['Beginners','Small businesses','Marketers','Students'],ARRAY['design','graphic design','templates','social media']),
('design','Figma','figma','Collaborative interface design and prototyping in the browser.','Figma is a browser-based design tool for UI design, prototyping and design systems, with multiplayer editing, components, dev handoff and FigJam whiteboards.','https://www.figma.com','UI/UX design','freemium','Free starter plan; paid seats on the official pricing page.',true,true,ARRAY['Web','Windows','macOS','Android','iOS','API'],'Global',2012,ARRAY['Real-time collaborative editing','Components and design systems','Prototyping','Developer handoff and inspect','Plugins','FigJam whiteboards'],ARRAY['Designers','Product teams','Developers'],ARRAY['design','ui design','prototyping','collaboration']),
('design','Adobe Express','adobe-express','Quick design and editing tool for social content, using Adobe assets.','Adobe Express creates social posts, flyers and short videos from templates, with Adobe Stock assets, fonts and quick photo edits such as background removal.','https://www.adobe.com/express/','Graphic design','freemium','Free plan; premium plan on the official pricing page.',true,true,ARRAY['Web','Android','iOS'],'Global',2021,ARRAY['Template-based design','Background removal','PDF and image conversion tools','Adobe Fonts and Stock access','Short video editing'],ARRAY['Beginners','Creators','Small businesses'],ARRAY['design','graphic design','templates','adobe']),
('design','Adobe Photoshop','adobe-photoshop','Professional raster image editing and compositing.','Photoshop is Adobe''s image editor for photo retouching, compositing and digital painting, with layers, masks, extensive selection tools and generative editing features.','https://www.adobe.com/products/photoshop.html','Photo editing','paid','Subscription plans with a trial; see the official pricing page.',false,true,ARRAY['Windows','macOS','iOS','Web'],'Global',1990,ARRAY['Layer-based editing','Advanced selection and masking','Photo retouching','Generative fill','Wide file format support'],ARRAY['Designers','Photographers','Professionals'],ARRAY['photo editing','design','image editor','adobe']),
-- PRODUCTIVITY
('productivity','Notion','notion','Connected workspace for notes, docs, wikis and databases.','Notion combines documents, wikis and flexible databases in one workspace, with views such as tables, boards and calendars, templates, and team permissions.','https://www.notion.com','Notes and wiki','freemium','Free personal plan; paid plans on the official pricing page.',true,true,ARRAY['Web','Windows','macOS','Android','iOS','API'],'Global',2016,ARRAY['Docs and nested pages','Flexible databases with multiple views','Templates','Team wikis and permissions','API and integrations','AI features on paid add-on'],ARRAY['Students','Startups','Teams','Freelancers'],ARRAY['notes','wiki','project management','productivity']),
('productivity','Trello','trello','Kanban boards for tracking tasks and simple projects.','Trello organises work as cards on boards, with lists, labels, due dates, checklists, automation rules and power-up integrations.','https://trello.com','Project management','freemium','Free plan; paid plans on the official pricing page.',true,true,ARRAY['Web','Android','iOS','Windows','macOS','API'],'Global',2011,ARRAY['Kanban boards','Checklists and due dates','Butler automation rules','Power-up integrations','Calendar and timeline views on paid plans'],ARRAY['Beginners','Small teams','Freelancers'],ARRAY['project management','kanban','tasks','productivity']),
('productivity','Asana','asana','Work management for tasks, projects and team workflows.','Asana tracks tasks and projects with list, board, timeline and calendar views, dependencies, custom fields, workflow rules and reporting dashboards.','https://asana.com','Project management','freemium','Free plan for small teams; paid tiers on the official pricing page.',true,true,ARRAY['Web','Android','iOS','Windows','macOS','API'],'Global',2008,ARRAY['Task and project tracking','Timeline and board views','Dependencies and milestones','Custom fields and forms','Workflow automation','Reporting dashboards'],ARRAY['Teams','Project managers','Businesses'],ARRAY['project management','tasks','collaboration','productivity']),
('productivity','ClickUp','clickup','Configurable project management with docs, tasks and dashboards.','ClickUp offers tasks, docs, whiteboards, goals and dashboards with many view types and configuration options, aiming to replace several separate tools.','https://clickup.com','Project management','freemium','Free forever plan; paid plans on the official pricing page.',true,true,ARRAY['Web','Android','iOS','Windows','macOS','API'],'Global',2017,ARRAY['Multiple task views','Docs and whiteboards','Custom fields and statuses','Automations','Dashboards and reporting','Time tracking'],ARRAY['Teams','Startups','Agencies'],ARRAY['project management','tasks','docs','productivity']),
('productivity','Todoist','todoist','Task manager for personal and shared to-do lists.','Todoist captures tasks with natural language dates, projects, labels, filters, recurring tasks and shared projects across desktop, mobile and browser.','https://www.todoist.com','Task management','freemium','Free plan; paid plans on the official pricing page.',true,true,ARRAY['Web','Android','iOS','Windows','macOS','API'],'Global',2007,ARRAY['Natural-language task entry','Projects and labels','Recurring tasks','Filters and priorities','Shared projects'],ARRAY['Students','Professionals','Freelancers'],ARRAY['tasks','to do list','productivity','planning']),
('productivity','Airtable','airtable','Spreadsheet-database hybrid for structured team data and workflows.','Airtable stores structured records in bases with typed fields, multiple views, forms, automations and an API, used for content calendars, inventories and internal tools.','https://www.airtable.com','Database and apps','freemium','Free plan; paid plans on the official pricing page.',true,true,ARRAY['Web','Android','iOS','API'],'Global',2012,ARRAY['Typed fields and relational links','Grid, kanban and calendar views','Forms','Automations','Interface designer','REST API'],ARRAY['Teams','Operations','Startups'],ARRAY['database','spreadsheet','no-code','productivity']),
-- COMMUNICATION
('communication','Slack','slack','Team messaging with channels, threads and app integrations.','Slack organises team communication into channels with threads, huddles for quick calls, searchable history and a large integration directory.','https://slack.com','Team chat','freemium','Free plan with history limits; paid plans on the official pricing page.',true,true,ARRAY['Web','Windows','macOS','Linux','Android','iOS','API'],'Global',2013,ARRAY['Channels and threads','Huddles audio/video','File sharing','App integrations and workflows','Searchable message history','Guest and external channels'],ARRAY['Teams','Startups','Enterprises'],ARRAY['team chat','messaging','collaboration','communication']),
('communication','Zoom','zoom','Video meetings, webinars and phone for teams.','Zoom provides video meetings with screen sharing, recording and transcripts, plus webinars, team chat and cloud phone services.','https://zoom.com','Video conferencing','freemium','Free plan with meeting length limits; paid plans on the official pricing page.',true,true,ARRAY['Web','Windows','macOS','Linux','Android','iOS','API'],'Global',2011,ARRAY['Video meetings','Screen sharing','Cloud recording and transcripts','Webinars','Breakout rooms','Team chat'],ARRAY['Teams','Educators','Enterprises'],ARRAY['video calls','meetings','webinar','communication']),
('communication','Google Meet','google-meet','Browser-based video meetings integrated with Google Calendar.','Google Meet runs video meetings from the browser or mobile apps, integrated with Google Calendar and Workspace, with recording and noise cancellation on paid tiers.','https://meet.google.com','Video conferencing','freemium','Free tier with limits; extra features via Google Workspace plans.',true,false,ARRAY['Web','Android','iOS'],'Global',2017,ARRAY['Browser-based meetings','Calendar integration','Screen sharing','Live captions','Recording on paid plans'],ARRAY['Teams','Students','Educators'],ARRAY['video calls','meetings','google','communication']),
('communication','Microsoft Teams','microsoft-teams','Chat, meetings and file collaboration inside Microsoft 365.','Microsoft Teams combines team chat, video meetings, calling and file collaboration with deep Microsoft 365 integration and enterprise administration.','https://www.microsoft.com/microsoft-teams/','Team collaboration','freemium','Free tier available; full features via Microsoft 365 plans.',true,true,ARRAY['Web','Windows','macOS','Android','iOS'],'Global',2017,ARRAY['Team chat and channels','Video meetings','SharePoint file collaboration','Calling features','Microsoft 365 integration'],ARRAY['Enterprises','Teams','Educators'],ARRAY['team chat','meetings','microsoft','communication']),
('communication','Discord','discord','Community servers with voice, video and text channels.','Discord hosts communities in servers with text, voice and video channels, roles and permissions, screen sharing and bots, widely used by gaming and interest communities.','https://discord.com','Community chat','freemium','Free to use; Nitro subscription adds cosmetic and upload perks.',true,false,ARRAY['Web','Windows','macOS','Linux','Android','iOS','API'],'Global',2015,ARRAY['Text, voice and video channels','Roles and permissions','Screen sharing','Bots and integrations','Community server tools'],ARRAY['Communities','Gamers','Creators'],ARRAY['chat','community','voice','communication']),
-- TRAVEL
('travel','Booking.com','booking-com','Search and book hotels, apartments and other stays worldwide.','Booking.com lists hotels, apartments and other accommodation with filters, reviews from verified stays, free-cancellation options and flight and car rental booking.','https://www.booking.com','Accommodation','free','Free to search and book; prices set by properties.',true,false,ARRAY['Web','Android','iOS'],'Global',1996,ARRAY['Hotel and apartment search','Verified guest reviews','Free cancellation options','Flights and car rentals','Loyalty discounts'],ARRAY['Travellers','Families','Business travellers'],ARRAY['travel','hotels','booking','stays']),
('travel','Airbnb','airbnb','Book stays in homes and apartments, plus experiences.','Airbnb connects travellers with hosts offering homes, apartments and rooms, with filters, reviews, messaging and cancellation policies set per listing.','https://www.airbnb.com','Accommodation','free','Free to search; service fees apply to bookings.',true,false,ARRAY['Web','Android','iOS'],'Global',2008,ARRAY['Home and apartment stays','Host and guest reviews','Filters for amenities','In-app messaging','Experiences'],ARRAY['Travellers','Families','Remote workers'],ARRAY['travel','stays','accommodation','booking']),
('travel','MakeMyTrip','makemytrip','Indian travel booking platform for flights, hotels, trains and buses.','MakeMyTrip books domestic and international flights, hotels, holiday packages, trains, buses and cabs, primarily for travellers from India.','https://www.makemytrip.com','Travel booking','free','Free to search and book; fees vary by booking.',true,false,ARRAY['Web','Android','iOS'],'India',2000,ARRAY['Flight booking','Hotel booking','Train and bus tickets','Holiday packages','Fare alerts'],ARRAY['Travellers','Families','Business travellers'],ARRAY['travel','flights','hotels','india']),
('travel','Skyscanner','skyscanner','Compare flight, hotel and car hire prices across providers.','Skyscanner searches flights, hotels and car hire across airlines and agents, with flexible date and everywhere searches and price alerts.','https://www.skyscanner.net','Flight search','free','Free to search; bookings completed with airlines or agents.',true,false,ARRAY['Web','Android','iOS'],'Global',2003,ARRAY['Flight price comparison','Flexible date search','Everywhere destination search','Price alerts','Hotel and car hire search'],ARRAY['Travellers','Budget travellers'],ARRAY['travel','flights','price comparison','booking']),
-- ENTERTAINMENT
('entertainment','Netflix','netflix','Subscription streaming service for films and series.','Netflix streams licensed and original films, series and documentaries, with profiles, downloads for offline viewing and plan tiers that vary by resolution and ads.','https://www.netflix.com','Video streaming','paid','Subscription tiers vary by country; see the official pricing page.',false,false,ARRAY['Web','Android','iOS','Windows','macOS'],'Available in most countries',1997,ARRAY['Films and series streaming','Original productions','Offline downloads','Multiple profiles','Subtitles and dubbing'],ARRAY['General internet users','Households'],ARRAY['streaming','movies','tv shows','entertainment']),
('entertainment','Spotify','spotify','Music and podcast streaming with playlists and recommendations.','Spotify streams music and podcasts with algorithmic and editorial playlists, an ad-supported free tier and Premium plans that add offline listening.','https://www.spotify.com','Music streaming','freemium','Free ad-supported tier; Premium plans on the official pricing page.',true,true,ARRAY['Web','Android','iOS','Windows','macOS'],'Available in most countries',2006,ARRAY['Music and podcast streaming','Personalised playlists','Offline listening on Premium','Cross-device playback','Shared and collaborative playlists'],ARRAY['General internet users','Students','Commuters'],ARRAY['music','streaming','podcasts','entertainment']),
('entertainment','YouTube','youtube','Video platform for watching, uploading and live streaming.','YouTube hosts user-uploaded and professional video, live streams and music, with a free ad-supported experience and a Premium subscription that removes ads.','https://www.youtube.com','Video platform','freemium','Free with ads; Premium subscription available.',true,true,ARRAY['Web','Android','iOS','API'],'Global',2005,ARRAY['Video hosting and streaming','Live streaming','Channel subscriptions','Playlists','Creator monetisation','Premium ad-free viewing'],ARRAY['General internet users','Creators','Students'],ARRAY['video','streaming','learning','entertainment']),
-- HEALTH & WELLNESS
('health-wellness','MyFitnessPal','myfitnesspal','Food and exercise logging with a large nutrition database.','MyFitnessPal logs meals and workouts against calorie and macro goals, with barcode scanning, a large food database and integrations with fitness trackers.','https://www.myfitnesspal.com','Nutrition tracking','freemium','Free plan; Premium subscription on the official pricing page.',true,true,ARRAY['Web','Android','iOS'],'Global',2005,ARRAY['Food and calorie logging','Large nutrition database','Barcode scanning','Exercise tracking','Fitness tracker integrations'],ARRAY['General internet users','Fitness beginners'],ARRAY['fitness','nutrition','calorie tracking','health']),
('health-wellness','Headspace','headspace','Guided meditation, mindfulness and sleep content.','Headspace offers guided meditation courses, focus music, sleepcasts and short mindfulness exercises through its app and web player.','https://www.headspace.com','Meditation','paid','Subscription with a trial period; see the official pricing page.',false,true,ARRAY['Web','Android','iOS'],'Global',2010,ARRAY['Guided meditation courses','Sleep content','Focus music','Short mindfulness exercises','Progress tracking'],ARRAY['Beginners','Professionals','Students'],ARRAY['meditation','mindfulness','sleep','wellness']),
('health-wellness','Practo','practo','Find doctors, book appointments and consult online in India.','Practo lets users search doctors and clinics, book appointments, consult online and order medicines or diagnostic tests in supported Indian cities.','https://www.practo.com','Healthcare','free','Free to search; consultation and service fees apply.',true,false,ARRAY['Web','Android','iOS'],'India',2008,ARRAY['Doctor search and reviews','Appointment booking','Online consultations','Diagnostic test booking','Health records'],ARRAY['General internet users','Families'],ARRAY['healthcare','doctors','telemedicine','india']),
-- FREELANCING
('freelancing','Upwork','upwork','Marketplace connecting freelancers with clients across skill categories.','Upwork lists client projects and lets freelancers submit proposals, with contracts, time tracking, milestone payments and payment protection.','https://www.upwork.com','Freelance marketplace','free','Free to join; service fees apply to earnings and payments.',true,false,ARRAY['Web','Android','iOS'],'Global',2015,ARRAY['Job listings and proposals','Hourly and fixed-price contracts','Time tracking','Milestone payments','Payment protection','Talent search for clients'],ARRAY['Freelancers','Small businesses','Startups'],ARRAY['freelancing','hiring','remote work','marketplace']),
('freelancing','Fiverr','fiverr','Marketplace where freelancers sell packaged services as gigs.','On Fiverr, freelancers publish service packages with fixed scope and price, and buyers order directly. Categories include design, writing, video, programming and marketing.','https://www.fiverr.com','Freelance marketplace','free','Free to join; service fees apply to orders and earnings.',true,false,ARRAY['Web','Android','iOS'],'Global',2010,ARRAY['Packaged service listings','Fixed-price ordering','Seller levels and reviews','Order messaging','Buyer requests'],ARRAY['Freelancers','Small businesses','Startups'],ARRAY['freelancing','gigs','hiring','marketplace']),
('freelancing','Toptal','toptal','Vetted network of freelance developers, designers and finance experts.','Toptal screens freelancers before admitting them to its network and matches clients with vetted talent for longer-term engagements, at higher rates than open marketplaces.','https://www.toptal.com','Freelance network','contact','Rates and engagement pricing are quoted per project; contact for pricing.',false,false,ARRAY['Web'],'Global',2010,ARRAY['Screened freelancer network','Client matching','Trial period on engagements','Developer, design and finance talent'],ARRAY['Enterprises','Startups','Experienced freelancers'],ARRAY['freelancing','hiring','developers','talent'])
) AS v(cat, name, slug, description, long_description, official_url, subcategory, pricing_type, price_description, has_free_plan, has_free_trial, platforms, availability, founded_year, features, best_for, tags)
LEFT JOIN public.categories c ON c.slug = v.cat;